### ISSUE TITLE
2 factor authentication fails

### ISSUE THREAD

**Issue by isaacdre** [luigiinred/Issues-for-Issues#20]
My security requirements need 2 factor enabled. Not an option to disable it for connecting to this app.

When a login attempt is made and 2 factor is on, I receive the auth code via text but the app has no way of entering the code.

**Comment by isaacdre** [comment]
When can we expect this to be updated in the app-store?

**Comment by luigiinred** [comment]
This should be available now. Apple approved it Friday. Are you still having this issue?

**Comment by isaacdre** [comment]
Just loaded the new update. It 2 factor works thanks!
